### PR TITLE
Support for interoperability between Accord and non-Accord managed data

### PR DESCRIPTION
**Pull request by aweisberg**
Incomplete/in progress checkpoint of interoperability improvements for monotonic reads

Checkpoint for safety

More checkpoint

Fix various problems with consistency levels and commit cl, add some tests to Accord

Need to handle merge for reduce specially to avoid NPE

### CODE REVIEW

**Comment by bdeggleston** [comment]
Did you explore implementing interop reads as another Read/Query/Write implementation in C*? I’m still looking at things at a high level and haven’t gotten into a detailed review yet, but seeing C* query implementation details start appearing in accord with classes like `DataResolver` etc immediately stands out to me as something we should avoid if possible. Ideally, I think interop should be almost entirely part of the C* implementation, with accord changes just providing C* the tools it needs to do that correctly.

In the case of reads w/ read repair, I think this could be implemented in C* if we gave the `Read` bit more latitude to determine which replicas are read from so we read from a quorum, with data resolution being performed by the `Query`, and any repairs being performed as the `Write`.

WDYT about this?

**Comment by aweisberg** [comment]
It's probably possible to push more of the data resolution plumbing behind the integration interface without passing references to unresolved data and repair writes in Accord. `Data` could refer to a lot of things and Accord mostly doesn't care.

`DataResolver` is separate because it seemed cleaner to separate responsibilities from `Read` since it needs to be possible to ask `Accord` to send additional reads, but we could move that into the `Read` interface. That's pretty fungible.

Accord already does replica selection and has to track the responses since it coordinates the transaction so what is it the integration can contribute there? Are you proposing moving coordination out of Accord?

**Comment by bdeggleston** [comment]
> Are you proposing moving coordination out of Accord?

No, I think I was imagining the read telling accord how many data responses to get, but thinking about that a bit more I guess having a read consistency level on the accord side would probably make the most sense here

**Comment by aweisberg** [comment]
Replaced by https://github.com/aweisberg/cassandra-accord/pull/3

**Pull request closed without merging**
